[App]
Mode = "development" # development, release, test, product

[Http]
Port = 9800

[Swagger]
BaseRoute = "doc"
Title = "Api"
Description = "Api Docs"
BasePath = "/v1"
Version = "1.0.0"

[Redis]
Addresses = ["10.58.144.6:36379"]
Password = "xixi@0202"
DB = 0

[Postgres]
Username = "postgres"
Password = "xixi@0202"
Database = "atom"
Host = "10.58.144.6"
Port = 30432

[OAuth]
[[OAuth.App]]
Name="app"
ClientID = "asdfasdfasdf"
ClientSecret = "asdfasdfasfdasfdasdf"
CallbackUrl = "http://www.baidu.com/auth/callback"
RegisterFields = ["username", "phone", "password"]
PasswordComplexRule = { MinLength = 6, MaxLength = 16, UpperCase = 1, SpecialChars = 1 }

[[OAuth.App]]
Name="app1"
ClientID = "asdfasdfasdf"
ClientSecret = "asdfasdfasfdasfdasdf"
