[App]
Mode = "development" # development, release, test, product

[Http]
Port = 9800

[Swagger]
BaseRoute = "doc"
Title = "Api"
Description = "Api Docs"
BasePath = "/v1"
Version = "1.0.0"

[Redis]
Addresses = ["10.58.144.6:36379"]
Password = "xixi@0202"
DB = 0
# [Redis]
# Addresses = ["localhost:6379"]
# Password = ""
# DB = 0

[MySQL]
Username = "root"
Password = "xixi@0202"
Database = "atom"
Host = "10.58.144.6"
Port = 33306

# [MySQL]
# Username = "root"
# Password = "admin"
# Database = "atom"
# Host = "localhost"
# Port = 3306

[OAuth]
[OAuth.App]
ClientID = "asdfasdfasdf"
ClientSecret = "asdfasdfasfdasfdasdf"
CallbackUrl = "http://www.baidu.com/auth/callback"
RegisterFields = ["username", "phone", "password"]
PasswordComplexRule = { MinLength = 6, MaxLength = 16, UpperCase = 1, SpecialChars = 1 }

[Casbin]
AdapterTableName="permission_rules"
Model = """
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[matchers]
m = is_white(r.obj, r.act) || g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch3(r.obj, p.obj) && r.act == p.act

[policy_effect]
e = some(where (p.eft == allow))
"""
# m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act